    env: "local" # local, dev, prod
    storage_path: "./storage/storage.db"
    http_server:
      address: "localhost:8082"
      timeout: 4s # time to read the user request
      idle_timeout: 60s # waiting time
      user: "user1"
      password: "pass1"
